# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_areas', '0001_initial'),
        ('sedes', '0001_initial'),
        ('areas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipos_areas_funcionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Sede'),
        ),
        migrations.AddField(
            model_name='area',
            name='tipo_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_areas.TipoArea'),
        ),
        migrations.AddField(
            model_name='area',
            name='tipo_area_funcional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_areas_funcionales.TipoAreaFuncional'),
        ),
        migrations.AddField(
            model_name='area',
            name='ultimo_usuario_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_area_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
