# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_identificaciones', '0002_auto_20160901_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoidentificacion',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Escribir el nombre del documento de Identificación.', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='documentoidentificacion',
            name='numero_digito',
            field=models.PositiveSmallIntegerField(help_text='Ingresar el número de dígitos total del documento de indetificación.', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2)], verbose_name='Número dígito(s)'),
        ),
        migrations.AlterField(
            model_name='documentoidentificacion',
            name='siglas',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
