# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 18:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_sitios_web', '0003_auto_20161003_2304'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('url', models.URLField(db_index=True, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional)')),
                ('tipo_sitio_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_sitios_web.TipoSitioWeb')),
                ('ultimo_usuario_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios_web_sitioweb_related', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Sitios_Web',
                'ordering': ('url',),
                'verbose_name': 'Sitio Web',
                'verbose_name_plural': 'Sitios Web',
            },
        ),
    ]
