# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20161107_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ocupacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocupaciones.Ocupacion', verbose_name='Ocupación'),
        ),
    ]
