# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-08 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empadronados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empadronado',
            old_name='descripcion_empedronado',
            new_name='descripcion_empadronado',
        ),
        migrations.RenameField(
            model_name='empadronado',
            old_name='observacion_empedronado',
            new_name='observacion_empadronado',
        ),
    ]
