# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 18:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empadronados', '0002_auto_20161108_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empadronado',
            name='celular',
            field=models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='empadronado',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='empadronado',
            name='estado_civil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empadronados_empadronado_related', to='estados_civiles.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='empadronado',
            name='grupo_sanguineo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empadronados_empadronado_related', to='grupos_sanguineos.GrupoSanguineo', verbose_name='Grupo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='empadronado',
            name='telefono',
            field=models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Télefono'),
        ),
    ]
