# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import infos_sistemas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('empadronados', '0003_auto_20161111_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='empadronado',
            name='codigo_barra_qr',
            field=models.ImageField(blank=True, default='default/No_Avatar_1.png', help_text='Subir Código Barra QR (Opcional).', null=True, upload_to='empadronado_codigo_barra_qr', validators=[infos_sistemas.validators.valid_extension], verbose_name='QR (Fotografía)'),
        ),
    ]
