# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 16:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('grupos_modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoModuloMenuSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('orden_modulo', models.SmallIntegerField(default=0)),
                ('orden_menu', models.SmallIntegerField(default=0)),
                ('orden_sub_menu', models.SmallIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, help_text='Subir imagen. (Opcional)', null=True, upload_to='')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Observación')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('grupo_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos_modulos.GrupoModulo')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
            options={
                'ordering': ('orden_modulo',),
                'db_table': 'Catalogos_Modulos_Menus_Sub_Menus',
                'verbose_name_plural': 'Catalogos Módulos Menus Sub Menus',
                'verbose_name': 'Catalogo Módulo Menu Sub Menu',
            },
        ),
    ]
