# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos_modulos_menus_sub_menus', '0001_initial'),
        ('modulos', '0001_initial'),
        ('sub_menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomodulomenusubmenu',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.Modulo'),
        ),
        migrations.AddField(
            model_name='catalogomodulomenusubmenu',
            name='sub_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_menus.SubMenu'),
        ),
        migrations.AddField(
            model_name='catalogomodulomenusubmenu',
            name='ultimo_usuario_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos_modulos_menus_sub_menus_catalogomodulomenusubmenu_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogomodulomenusubmenu',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
