# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_modulos_menus_sub_menus', '0002_auto_20161107_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogomodulomenusubmenu',
            options={'ordering': ('orden_modulo', 'orden_menu', 'orden_sub_menu'), 'verbose_name': 'Catalogo Módulo Menu Sub Menu', 'verbose_name_plural': 'Catalogos Módulos Menus Sub Menus'},
        ),
    ]
