# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 18:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vias', '0002_auto_20161003_2304'),
        ('distritos', '0004_auto_20161003_2304'),
        ('zonas', '0002_auto_20161003_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona_via', models.CharField(db_index=True, help_text='Escribir nombre (Zona/Vía).', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre (Zona/Vía)')),
                ('denominacion', models.CharField(blank=True, help_text='(Opcional).', max_length=255, null=True, verbose_name='Denominación')),
                ('observacion_zona_via', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación (Zona/Vía)')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_ubicacion_related', to='distritos.Distrito')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_ubicacion_related', to='vias.Via')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_ubicacion_related', to='zonas.Zona')),
            ],
        ),
    ]
