# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='via',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_ubicacion_related', to='vias.Via'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='zona',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_ubicacion_related', to='zonas.Zona'),
        ),
    ]
