# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_auto_20161107_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='denominacion',
        ),
    ]
