# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_auto_20160901_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo_postal',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(3)], verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Subir imagen del departamento. (Opcional)', null=True, upload_to='imagenes_departamentos'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Escribir el nombre del departamento.', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
