# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_auto_20161003_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo_postal',
            field=models.PositiveIntegerField(unique=True, verbose_name='Código postal'),
        ),
    ]
